In [2]:
import torch

# 示例数据
tensor = torch.randn(20, 208)
print(tensor)
array = torch.ones(20)
print(array)

# 使用广播进行逐元素相乘
result = tensor * array[:, None]
print(result)

print(result.shape)

tensor([[ 0.3137, -0.2343, -0.2598,  ...,  0.3202,  0.1208,  0.3160],
        [-0.3530,  0.3746, -0.6394,  ...,  1.2815, -1.0512,  0.4020],
        [-0.3342,  0.7872,  1.1393,  ...,  0.9954,  0.3982, -0.1756],
        ...,
        [ 1.0368, -1.5813, -1.3166,  ..., -0.2105,  0.2834, -0.0563],
        [ 0.4424,  0.2943, -0.7222,  ...,  0.5979, -0.2894,  0.5395],
        [-0.8879, -1.5638,  0.0421,  ...,  0.0127, -0.8769, -0.4331]])
tensor([ 1.1524,  0.4685, -0.4043, -0.2357,  0.7016, -1.8937, -0.8826,  0.7821,
         1.8177, -1.4871,  0.1369, -0.9920,  0.8324,  2.4257,  0.4230,  0.8006,
        -0.0288,  0.6204, -0.0035,  0.1284])
tensor([[ 0.3615, -0.2701, -0.2994,  ...,  0.3690,  0.1392,  0.3641],
        [-0.1654,  0.1755, -0.2996,  ...,  0.6004, -0.4925,  0.1883],
        [ 0.1351, -0.3182, -0.4606,  ..., -0.4024, -0.1610,  0.0710],
        ...,
        [ 0.6432, -0.9810, -0.8168,  ..., -0.1306,  0.1758, -0.0349],
        [-0.0015, -0.0010,  0.0025,  ..., -0.0021,  0.0010, -0.0019]

In [2]:
import numpy as np

# 假设你有多个坐标数组
coordinates1 = np.array([[1, 2], [3, 4]])
coordinates2 = np.array([[-1, -2], [-3, -4]])
coordinates3 = np.array([[5, 6], [7, 8]])

# 使用np.concatenate拼接多个坐标数组
concatenated_coordinates = np.concatenate((coordinates1, coordinates2, coordinates3), axis=0)

# 输出拼接后的坐标数组
print(concatenated_coordinates)

[[ 1  2]
 [ 3  4]
 [-1 -2]
 [-3 -4]
 [ 5  6]
 [ 7  8]]


In [3]:
import numpy as np

# 指定范围和坐标数量
x_min, x_max = -5, 5
y_min, y_max = -10, 10
num_points = 20

# 生成随机二维坐标数组
coordinates = np.random.uniform(low=[x_min, y_min], high=[x_max, y_max], size=(num_points, 2))

# 输出生成的坐标数组
print(coordinates)

[[ 4.95421144 -0.33070105]
 [ 2.76442321  2.8665593 ]
 [ 1.43510268  6.48145762]
 [ 1.97998607 -1.20769878]
 [-2.20094633 -9.26259   ]
 [-1.90915286 -9.28809286]
 [-1.21387105  8.57863729]
 [ 4.79646532  7.80184994]
 [ 4.91048413 -0.5817656 ]
 [ 2.86792761  6.08856682]
 [ 0.91605945 -1.19011172]
 [ 2.76795229  3.14863458]
 [ 0.93103147  6.72381333]
 [ 0.21805831 -3.08385264]
 [ 0.78999723 -8.67441866]
 [ 4.53464525 -5.80838098]
 [ 0.39090905 -0.10051034]
 [ 3.17428622 -6.36454641]
 [ 3.10644563  1.37178036]
 [ 0.47271897  0.49039984]]


In [2]:
import torch
import torch.nn as nn

loss = nn.CrossEntropyLoss()
input1 = torch.randn(3, 5, requires_grad=True)
print(input1)
target = torch.empty(3, dtype=torch.long).random_(5)
print(target)
output = loss(input1, target)
print(output)

tensor([[-0.4299,  0.7589, -2.3195, -1.4332, -1.0441],
        [ 0.7392, -0.2756,  1.6840, -1.3824,  0.9535],
        [ 0.1019,  1.0550, -1.6938, -0.3221, -1.5224]], requires_grad=True)
tensor([3, 4, 3])
tensor(2.0278, grad_fn=<NllLossBackward>)


In [ ]:
import numpy as np
weights = np.linspace(1.0, 0.0, 10)
print(weights)

: 

In [ ]:
from flask import Flask, render_template, request, jsonify
import logging
import os
import time

import sys
sys.path.append("./python_files")
import my_tools

import torch
import torch.nn as nn
from torch.utils.data import DataLoader
from torch.utils.data import Dataset
import matplotlib.pyplot as plt
import sys
import pickle
from scipy import spatial
python_files_dir = "./python_files/" # python工具包位置
sys.path.append(python_files_dir)

model_files_dir = "./model_files/" # 模型位置
sys.path.append(model_files_dir)
import model_files as model_all

device_id = 2
device = torch.device("cuda:" + str(device_id)) 

import torch
import torch.nn as nn
import sys
python_files_dir = "./python_files/" # python工具包位置
sys.path.append(python_files_dir)
import fid_score as official_fid

model_files_dir = "./model_files/" # 模型位置
sys.path.append(model_files_dir)
from CIFAR10.models import ResNet20 as ResNet
from CIFAR10.models import Rob_predictor as my_Rob_predictor

import foolbox as fb
from foolbox.attacks import LinfPGD


import pickle
import os
import numpy as np
from tqdm import tqdm
from PIL import Image  
from sklearn.manifold import TSNE
import matplotlib.pyplot as plt
from scipy import spatial
import time
import PIL.Image
import copy
import eagerpy as ep

import torch
import torchvision.utils as utils
from torch.utils.data import DataLoader
from torchvision import datasets
import torchvision.transforms as transforms
from torch.utils.data import Dataset
from torch.autograd import Variable
import random



#kjl测试####################################################start
# 定义VAE模型
class VAE(nn.Module):
    def __init__(self, latent_dim):
        super(VAE, self).__init__()

        self.latent_dim = latent_dim

        # 编码器
        self.encoder = nn.Sequential(
            nn.Linear(208, 512),
            nn.ReLU(),
            nn.Linear(512, 256),
            nn.ReLU(),
        )
        self.fc_mu = nn.Linear(256, latent_dim)
        self.fc_logvar = nn.Linear(256, latent_dim)

        # 解码器
        self.decoder = nn.Sequential(
            nn.Linear(latent_dim, 256),
            nn.ReLU(),
            nn.Linear(256, 512),
            nn.ReLU(),
            nn.Linear(512, 208),
            nn.Sigmoid()
        )

    def encode(self, x):
        x = self.encoder(x)
        mu = self.fc_mu(x)
        logvar = self.fc_logvar(x)
        return mu, logvar

    def reparameterize(self, mu, logvar):
        std = torch.exp(0.5 * logvar)
        eps = torch.randn_like(std)
        z = mu + eps * std
        return z
    
    def get_2D(self, x):
        mu, logvar = self.encode(x.view(-1, 208))
        z = self.reparameterize(mu, logvar)
        return z

    def decode(self, z):
        x = self.decoder(z)
        return x

    def forward(self, x):
        mu, logvar = self.encode(x.view(-1, 208))
        z = self.reparameterize(mu, logvar)
        x_recon = self.decode(z)
        return x_recon, mu, logvar

vae_path = os.path.join("./临时垃圾-随时可删/20230814vae训练", "vae_state_dict_epoch = 100 kl = 0.01 cl_w = 3.0 loss = 0.13633339115142823 loss_fn=official 2023-08-17 20:33:18.pt")
# 初始化VAE模型
vae = VAE(2)
vae.load_state_dict(torch.load(vae_path, map_location=device))
vae = vae.to(device)
vae.eval()
# 加载数据集
# 自定义datasets
class Mydata_sets__(Dataset):
    def __init__(self, path, device, transform=None):
        super(Mydata_sets__, self).__init__()
        self.latent_z = torch.load(path, map_location=device)

    def __getitem__(self, index):
        z = self.latent_z[index].detach()
        return z

    def __len__(self):
        return len(self.latent_z)

datasets = Mydata_sets__('./static/data/CIFAR10/latent_z/BigGAN_random_50k_png_208z_50000.pt', device = device)
dataLoader = DataLoader(datasets, batch_size=32, shuffle=True)
with torch.no_grad():
    for i, data in enumerate(dataLoader):
        data = data.to(device)
        if i == 0:
            z_2ds = vae.get_2D(data)
        else:
            z_2d = vae.get_2D(data)
            z_2ds = torch.cat((z_2ds, z_2d))
print("z_2ds.shape: ", z_2ds.shape)
# 将张量转换为 NumPy 数组
zs_np = z_2ds.to(torch.device("cpu")).detach().numpy()

# 画图检查
plt.scatter(zs_np[:, 0], zs_np[:, 1], s=0.05)
plt.xlabel('Dimension 1')
plt.ylabel('Dimension 2')
# 保存图像
plt.savefig('test_vae.png') 

# 建立搜索树
kdTree_2D = spatial.KDTree(data=zs_np)
data_z_path="./static/data/CIFAR10/latent_z/BigGAN_random_50k_png_208z_50000.pt"
latent_z = torch.load(data_z_path, map_location="cpu") #因为我之前保存数据到了GPU上，所以要回到cpu上才不会出错

k = 10000
coordinates = [[0,0]]
nearest_distance, nearest_index = kdTree_2D.query(coordinates, k=k)
origin_coordinates = kdTree_2D.data # 获取kdtree中原始的坐标
for i, pos in enumerate(coordinates): #对每一个坐标进行插值
    # pos坐标对应的近邻下标
    pos_nearst_index = nearest_index[i] # 其中有k个index，每个index对应kdTree_2D中的一个2维坐标
    pos_nearst_distance = nearest_distance[i]

    ##########################test
    # print("当前坐标：", pos)
    # for j in range(len(pos_nearst_index)):
    #     print("最近的坐标：", origin_coordinates[pos_nearst_index[j]])
    #     print("最近的距离：", pos_nearst_distance[j])
    #     print("对应的类向量：", latent_z[pos_nearst_index[j]][-128:])
    # print("暂时结束")
    # return
    ##########################end

    # 最近邻的坐标点，以及最近的距离
    most_nearst_pos = origin_coordinates[pos_nearst_index[0]]
    most_nearst_dis = pos_nearst_distance[0]

    # 利用三角形,找到第二个插值基点，让两边之和越接近第三边，就越是钝角，就越合理
    s1 = most_nearst_dis
    best_index = 1 # 默认第二个最近邻最好
    min_dif = 100

    fun_dic = {}
    for j in range(1, k):
        cur_pos = origin_coordinates[pos_nearst_index[j]]
        s2 = pos_nearst_distance[j]
        s3 = np.linalg.norm(most_nearst_pos-cur_pos)
        if (s1 + s2) - s3 < min_dif: # 两边之和大于等于第三边，所以不用绝对值
            min_dif = (s1 + s2) - s3
            best_index = j

        
        # 统计一下最近邻居中最多的类别###################test
        class_v = str(latent_z[pos_nearst_index[j]][-128:].detach().numpy())
        # print("当前类别向量：",class_v)
        if class_v in fun_dic.keys():
            fun_dic[class_v] += 1
        else:
            fun_dic[class_v] = 1
        # print(latent_z[pos_nearst_index[j]][-128:])
    print("当前数量向量数量为：", len(fun_dic.keys()))
    print("对应的值：", list(fun_dic.values()))
    if i > 20:
        break

: 

In [ ]:
import torch
device = torch.device("cuda:1") 
dataset_type = "SteeringAngle"
model_name = "null"
save_origin_pic = False # 是否保留原始图片
save_generate_pic = False # 是否保留生成图片
fid_judge = False # 是否进行fid评估

if dataset_type == "CIFAR10":
    ResNet50 = torch.load("./model_files/CIFAR10/checkpoints/classify_model/ResNet50.pt", map_location=device) # 这个pt文件里不仅仅是参数，包括了模型
    ResNet50 = ResNet50.to(device)
    ResNet50.eval()
    train_dataloader = DataLoader(datasets.CIFAR10('./static/data/CIFAR10/CIFAR10/', train=False, download=True, transform=transform), batch_size=128, shuffle=False)

class Mydata_sets(Dataset):
    
    def __init__(self, path, transform=None):
        super(Mydata_sets, self).__init__()
        self.root_dir = path
        self.img_names = os.listdir(self.root_dir)
        self.transform = transform

    def __getitem__(self, index):
        img_name = self.img_names[index]
        img = Image.open(os.path.join(self.root_dir, img_name))
        id_name = torch.tensor(int(img_name[4:-4])) #pic_xx.jpg
        if self.transform is not None:
            img = self.transform(img)
        return img, id_name

    def __len__(self):
        return len(self.img_names)

if dataset_type == "CIFAR10":
    transform = transforms.Compose([
        transforms.PILToTensor(),
        transforms.ConvertImageDtype(torch.float),
        transforms.Resize((224, 224), interpolation=Image.BICUBIC),
        transforms.Normalize((0.485, 0.456, 0.406), (0.229, 0.224, 0.225)),
    ])

index = 0
with torch.no_grad():
    train_dataloader = tqdm(train_dataloader)
    total = 0
    correct = 0
    for inputs, labels in train_dataloader:
            inputs,labels = inputs.to(device), labels.to(device)
            # ============= forward =============
            outputs = ResNet50(inputs)
            # ============= precision ===========
            _, predicted = torch.max(outputs.data, 1)
            total += labels.size(0)
            correct += (predicted == labels).sum().item()
            #break
            description = 'correct: %.4f, total: %.4f , accuracy: %.4f' % (correct, total, correct/total)
            train_dataloader.set_description(description)
            train_dataloader.update()
print("最终结果： ", description)


features, labels, ids = [], [], [] # features：提取的2048维图片特征，labels：模型预测的标签，ids图片文件编号

feature_model = copy.deepcopy(ResNet50)
feature_model.fc = nn.Identity() # 相当于取消fc层, 这样
label_model = copy.deepcopy(ResNet50)

# 图片路径
if dataset_type == "CIFAR10":
    pic_path = "./static/data/CIFAR10/pic/random_50k_png"   

img_datasets = Mydata_sets(pic_path, transform=transform)  
# img_datasets = torchvision.datasets.CIFAR10("./static/data/CIFAR10/", train=True, download=False, transform=transform) #使用原始的cifar10图片
imgLoader = torch.utils.data.DataLoader(img_datasets, batch_size=128, shuffle=False, num_workers=4)  # 指定读取配置信息

with torch.no_grad():
    for x, y in tqdm(imgLoader):
        x = x.to(device)
        ids.append(y)  # N
        feature = feature_model(x)  # N, 2048
        features.append(feature)

        ten_D = label_model(x)
        label = torch.argmax(ten_D, dim=1)
        labels.append(label)

features = torch.cat(features, dim=0).squeeze().cpu().numpy()  # (n, 2048)
labels = torch.cat(labels, dim=0).squeeze().cpu().numpy()  # n
ids = torch.cat(ids, dim=0).cpu().numpy() # n

print(features.shape)
print(labels.shape)
print(ids.shape)

: 

In [ ]:
import torch
device = torch.device("cuda:0")
a = torch.load("./static/data/CIFAR10/latent_z/BigGAN_random_50k_png_208z_50000.pt", map_location=device)
print(a[0][-128:])

: 

In [ ]:
torch.min(a)

: 

In [ ]:
import torch.nn as nn
import torch

shared = nn.Embedding(10, 128)
shared(torch.tensor(0))

: 

In [ ]:
def test(lis):
    lis[0] = 5

def main():
    lis = [0]*5
    print(lis)
    test(lis)
    print(lis)

main()

: 

In [ ]:
import torch
import random

# Set the device to CPU or GPU
device = 'cuda' if torch.cuda.is_available() else 'cpu'

# Generate a random tensor with a value between 0 and 0.3
value = random.uniform(0, 0.3)
tensor = torch.tensor(value).unsqueeze(0).to(device)

# Print the tensor
print(tensor)

: 

In [ ]:
import torch
import matplotlib.pyplot as plt
import numpy as np
# rob = torch.load("./系统以外的资源/对抗鲁棒性PDG/SteeringAngle/ResNet34_regre/PDG_robustness_ResNet34_regre.pt", map_location=torch.device("cpu"))
# rob = torch.load("./系统以外的资源/对抗鲁棒性PDG/CIFAR10/ResNet32/PDG_robustness_ResNet32.pt", map_location=torch.device("cpu"))
# rob = torch.load("./系统以外的资源/对抗鲁棒性PDG/SteeringAngle/ResNet34_regre/PDG_robustness_ResNet34_regre_wrongAngel=5epsilon=0.0005epsilon_step=0.0005.pt", map_location=torch.device("cpu"))
# rob = torch.load("./系统以外的资源/对抗鲁棒性PDG/SteeringAngle/ResNet34_regre/PDG_robustness_ResNet34_regre_wrong angel=8.0epsilon=0.001epsilon_step=0.001.pt", map_location=torch.device("cpu"))
# rob = torch.load("./系统以外的资源/对抗鲁棒性PDG/SteeringAngle/ResNet34_regre/PDG_robustness_ResNet34_regre_wrongAngel=5epsilon=0.0002epsilon_step=0.0002.pt", map_location=torch.device("cpu"))
# rob = torch.load("./系统以外的资源/对抗鲁棒性PDG/SteeringAngle/ResNet34_regre/PDG_robustness_ResNet34_regre_wrongAngel=10.0epsilon=0.001epsilon_step=0.001.pt", map_location=torch.device("cpu"))
# rob = torch.load("./系统以外的资源/对抗鲁棒性PDG/SteeringAngle/ResNet34_regre/PDG_robustness_ResNet34_regre_wrongAngel=15.0epsilon=0.001epsilon_step=0.001.pt", map_location=torch.device("cpu"))


# 创建一个大小为100的随机张量
x = torch.tensor(rob)
print(x.shape)
# 计算直方图及其边界
hist, bins = np.histogram(x.numpy(), bins=32, range=(0, 0.032))

# 绘制直方图
plt.hist(x.numpy(), bins=bins)
plt.show()

: 

In [ ]:
import eagerpy as ep
import torch

# 定义随机张量的形状和数据类型
x0 = ep.zeros((3, 3))

# 生成服从均匀分布的随机张量
epsilon = 0.1
rand_tensor = ep.uniform(x0, x0.shape, -epsilon, epsilon)

print(rand_tensor)  # 输出一个形状为 (3, 3) 的张量，数据类型为 float32

: 

In [ ]:
import torch

angles = torch.load("./static/data/SteeringAngle/angle/angles_50000.pt")

: 

In [ ]:
print(angles[:10])

: 

In [ ]:
import random

# 设置随机数生成器的种子为1
random.seed(1)

# 生成0到1之间的随机数
rand_num_1 = random.random()

# 再次生成0到1之间的随机数
rand_num_2 = random.random()

print(rand_num_1)
print(rand_num_2)

: 

In [ ]:
import random
random.randrange(10)

: 

In [ ]:
model_files_dir = "./model_files/" # 模型位置
sys.path.append(model_files_dir)
import model_files as model_all

import torch
import torch.nn as nn
import numpy as np


: 

In [ ]:
model_files_dir = "./model_files/" # 模型位置
sys.path.append(model_files_dir)
import model_files as model_all

import torch
import torch.nn as nn
import numpy as np

device = torch.device("cuda:0")

def sample_normal(batch_size, z_dim, truncation_factor, device):
    if truncation_factor == -1.0:
        latents = torch.randn(batch_size, z_dim, device=device)
    elif truncation_factor > 0:
        latents = torch.FloatTensor(truncated_normal([batch_size, z_dim], truncation_factor)).to(device)
    else:
        raise ValueError("truncated_factor must be positive.")
    return latents
def sample_y(y_sampler, batch_size, num_classes, device):
    if y_sampler == "totally_random":
        y_fake = torch.randint(low=0, high=num_classes, size=(batch_size, ), dtype=torch.long, device=device)

    elif y_sampler == "acending_some":
        assert batch_size % 8 == 0, "The size of batches should be a multiple of 8."
        num_classes_plot = batch_size // 8
        indices = np.random.permutation(num_classes)[:num_classes_plot]

    elif y_sampler == "acending_all":
        batch_size = num_classes * 8
        indices = [c for c in range(num_classes)]

    elif isinstance(y_sampler, int):
        y_fake = torch.tensor([y_sampler] * batch_size, dtype=torch.long).to(device)
    else:
        y_fake = None

    if y_sampler in ["acending_some", "acending_all"]:
        y_fake = []
        for idx in indices:
            y_fake += [idx] * 8
        y_fake = torch.tensor(y_fake, dtype=torch.long).to(device)
    return y_fake

def sample_zy(z_prior="gaussian", batch_size=80, z_dim=80, num_classes=10, truncation_factor=-1, y_sampler="totally_random", device=device):

    fake_labels = sample_y(y_sampler=y_sampler, batch_size=batch_size, num_classes=num_classes, device=device)
    batch_size = fake_labels.shape[0]

    if z_prior == "gaussian":
        zs = sample_normal(batch_size=batch_size, z_dim=z_dim, truncation_factor=truncation_factor, device=device)
    elif z_prior == "uniform":
        zs = torch.FloatTensor(batch_size, z_dim).uniform_(-1.0, 1.0).to(device)
    else:
        raise NotImplementedError
    return zs, fake_labels

checkpoints_path = "./model_files/CIFAR10/checkpoints/BigGAN/model=G-best-weights-step=162000.pth"
G = model_all.get_generative_model("CIFAR10").to(device)
G.load_state_dict(torch.load(checkpoints_path, map_location=device)["state_dict"])
G.eval()

zs, labels = sample_zy()
fake_images = G(zs, labels)
from torchvision.utils import save_image
save_image(((fake_images + 1)/2).clamp(0.0, 1.0), "./test.png", padding=0, nrow=8)

: 

: 

: 

In [ ]:
import torch
import torch.nn as nn

from torch.utils.data import DataLoader
import torch.optim as optim
from torchvision import datasets
import torchvision.transforms as transforms
from tqdm import tqdm


: 

In [ ]:
for i in range(3, 10):
    print(i)

: 

In [ ]:
import torch

a = torch.tensor([4,6,4])
b = torch.tensor([2,2,2])

a * b


: 

In [ ]:
import pickle
import torch
import torch.nn as nn
import torchvision
import numpy as np
import os
import matplotlib.pyplot as plt
os.environ["GIT_PYTHON_REFRESH"] = "quiet"
from foolbox import PyTorchModel, accuracy, samples
from foolbox.attacks import LinfPGD
import csv

from torchvision import transforms
from PIL import Image
from tqdm import tqdm
import model_files as model_all #模型的连接在__init__.py中体现

import argparse

'''
arg主要是模型选择参数
'''
parser = argparse.ArgumentParser()
parser.add_argument('--dataset', type=str, default="CIFAR10", help="数据集类别: CIFAR10或者MNIST")
parser.add_argument('--model_name', type=str, default="ResNet20", help="模型名字，例如ResNet20")
parser.add_argument('--weight_dir', type=str, default="./model_files/CIFAR10/checkpoints/classify_model/", help="模型参数的位置")
parser.add_argument('--epoch', type=str, default='199', help="决定用那个epoch的模型参数")
parser.add_argument('--gpu_id', type=str, default='0')
args = parser.parse_args()

# 设备检测
device = torch.device("cuda:" + args.gpu_id  if torch.cuda.is_available() else "cpu")

model = model_all.get_DNN_model(args.dataset,args.model_name)
model.load_state_dict(torch.load(args.weight_dir + args.model_name + '.pt'))
model.eval()
model = model.to(device)


#读取数据
pic_path = "./static/data/"+ args.dataset +"/pic/random_50k"
filenames = os.listdir(pic_path)
filenames.sort(key=lambda x: int(x[4:-4])) # pic_0.jpg,根据编号进行排序


if args.dataset == "MNIST":
    transform = transforms.Compose(
            [
                transforms.ToTensor(),
                transforms.Resize([32,32])
            ]
        )
    preprocessing = dict(mean=[0.5], std=[0.5], axis=-3)
elif args.dataset == "CIFAR10":
    transform = transforms.Compose(
            [
                transforms.ToTensor(),
                transforms.Normalize([0.4914,0.4822,0.4465], [0.2023,0.1994,0.2010])
            ]
        )
    preprocessing = dict(mean=[0.4914,0.4822,0.4465], std=[0.2023,0.1994,0.2010], axis=-3)


fmodel = PyTorchModel(model, bounds=(0, 1), device = device, preprocessing=preprocessing)
attack = LinfPGD()
arr=[]

#数据
robustness = []
for i, file in enumerate(filenames):
    position = pic_path + "/" + file
    if args.dataset == "MNIST":
        image = Image.open(position).convert('L')
    elif args.dataset == "CIFAR10":
        image = Image.open(position)
    input_image = transform(image)
    input_image = input_image.unsqueeze(0).to(device)  # 增加一个维度维batch维度
    print("image.shape:",input_image.shape)
    output = model(input_image)
    print(output)
    a = input("press 0 to break: ")
    if a == "0":
        break

: 

In [ ]:
import torch
import torch.nn as nn
import torch.optim as optim
import torch.nn.functional as F
import numpy as np
import os 
import time
from tqdm import tqdm
import codecs
import model_files as model_all #模型的连接在__init__.py中体现
from PIL import Image 
from torch.utils.data import Dataset
import torchvision.transforms as transforms
from torch.utils.data import DataLoader

pic_path = "./static/data/CIFAR10/pic/random_50k"
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")

transform = transforms.Compose([transforms.ToTensor(), transforms.Normalize([0.4914,0.4822,0.4465], [0.2023,0.1994,0.2010])])
robustness = torch.load("./系统以外的资源/对抗鲁棒性PDG/CIFAR10/ResNet20/PDG_robustness_ResNet20.pt")

class Mydata_sets(Dataset):
    
    def __init__(self, pic_path, pic_robustness, train, transform):
        super(Mydata_sets, self).__init__()
        self.root_dir = pic_path
        self.transform = transform
        filenames = os.listdir(pic_path)
        filenames.sort(key=lambda x: int(x[4:-4])) # pic_0.jpg,根据编号进行排序
        if(train == True):
            self.pic_filenames = filenames[:40000]
            self.pic_robustness = pic_robustness[:40000]
        else:
            self.pic_filenames = filenames[40000:]
            self.pic_robustness = pic_robustness[40000:]

    def __getitem__(self, index):
        img_name = self.pic_filenames[index]
        img = Image.open(os.path.join(self.root_dir, img_name))
        img = self.transform(img)
        pic_robustness = self.pic_robustness[index]
        return img, pic_robustness

    def __len__(self):
        return len(self.pic_filenames)


#读取模型数据
model = model_all.get_DNN_model("CIFAR10","ResNet20")
model.load_state_dict(torch.load("./model_files/CIFAR10/checkpoints/classify_model/ResNet20.pt"))
model.eval()
model = model.to(device)

test_dataloader = DataLoader(Mydata_sets(pic_path, robustness, False, transform = transform), batch_size=3, shuffle=False)

with torch.no_grad():
    for i, (inputs, robs) in enumerate(test_dataloader):
        inputs, robs = inputs.to(device),torch.tensor(robs).to(torch.float32).to(device)
        # =========== forward ==========
        penultimate_layer = model(inputs)

        print("penultimate_layer: ", penultimate_layer)
        a = input("press 0 to break: ")
        if a == "0":
            break

: 

In [ ]:
import torch
import torch.nn as nn

# 定义嵌入层
embedding = nn.Embedding(num_embeddings=100, embedding_dim=50)

# 定义输入序列
input_seq = torch.tensor([1, 1, 3, 4, 5])

# 将输入序列映射为嵌入向量
embedded_seq = embedding(input_seq)

# 输出嵌入向量
print(embedded_seq)

: 

In [ ]:
import numpy as np
from scipy.spatial import KDTree
points = np.array([(0, 0), (1, 0), (0, 1), (1, 1)])

# 创建 KD 树
tree = KDTree(points)
tree.data

: 

In [ ]:
import numpy as np

# 定义两个向量
v1 = np.array([0,0])
v2 = np.array([1,2])

# 计算两个向量之间的距离
distance = np.linalg.norm(v1 - v2)

print("向量 v1 和向量 v2 之间的距离为：", distance)

: 

In [ ]:
import numpy as np
from scipy.spatial import KDTree

# 创建一个二维数据集
points = np.array([(0, 0), (1, 0), (0, 1), (1, 1)])

# 创建 KD 树
tree = KDTree(points)

# 获取距离指定点最近的点及其距离
query_point = np.array([(0.5, 0.5)])
dist, ind = tree.query(query_point,k=2)
nearest_point = points[ind]
print("距离最近的点：", nearest_point)
print("距离：", dist)

: 

In [ ]:

device = torch.device("cuda:1")

: 

In [ ]:
# state_dict = torch.load("cifar10_resnet20.pt", map_location=device)
# model = ResNet.CifarResNet().to(device)
# model.load_state_dict(state_dict)

import torch
model = torch.hub.load("chenyaofo/pytorch-cifar-models", "cifar10_resnet20", pretrained=True)
model.eval()
model = model.to(device)


: 

In [ ]:
# transform = transforms.Compose([transforms.ToTensor(), transforms.Normalize([0.4914,0.4822,0.4465], [0.2023,0.1994,0.2010])]) #CIFAR10数据集的均值和方差，多处网络验证

transform = transforms.Compose([transforms.ToTensor(), transforms.Normalize([0.4914,0.4822,0.4465], [0.2023,0.1994,0.2010])])
train_dataloader = DataLoader(datasets.CIFAR10('./static/data/CIFAR10/CIFAR10', train=True, download=True, transform=transform), batch_size=128, shuffle=True)
test_dataloader = DataLoader(datasets.CIFAR10('./static/data/CIFAR10/CIFAR10', train=False, download=True, transform=transform), batch_size=256, shuffle=True)

: 

In [ ]:
test_dataloader = tqdm(test_dataloader)
total = 0
correct = 0
for inputs, labels in test_dataloader:
    inputs,labels = inputs.to(device),labels.to(device)
    # ============= forward =============
    outputs = model(inputs)
    # ============= precision ===========
    _, predicted = torch.max(outputs.data, 1)
    total += labels.size(0)
    correct += (predicted == labels).sum().item()
    description = '【测试集】correct: %.4f, total: %.4f , accuracy: %.4f' % (correct, total, correct/total)
    test_dataloader.set_description(description)
    test_dataloader.update()

: 

In [ ]:


import torch
import torchvision.models as models
from torchvision import transforms
import foolbox
import model_files as model_all #模型的连接在__init__.py中体现
from PIL import Image
import numpy as np

dataset="CIFAR10"
model_name="ResNet20"
weight_dir="./model_files/CIFAR10/checkpoints/classify_model/"
device = torch.device("cuda:0")
# 加载模型
model = model_all.get_DNN_model(dataset, model_name)
model.load_state_dict(torch.load(weight_dir + model_name + '.pt', map_location="cpu"))
model = model.to(device)
model.eval()

# 加载图像并预处理
pic_path = "./static/data/"+ dataset +"/pic/random_50k/pic_1.jpg"
image= Image.open(pic_path)
label=torch.tensor(6).unsqueeze(0).to(device)

preprocess = transforms.Compose([
    transforms.ToTensor()
])
preprocessing = dict(mean=[0.4914,0.4822,0.4465], std=[0.2023,0.1994,0.2010], axis=-3)
image = preprocess(image).to(device)
image = image.unsqueeze(0)  # 将图像增加一个维度，变成4D张量

# 创建一个Foolbox模型
fmodel = foolbox.models.PyTorchModel(model, bounds=(0, 1), preprocessing=preprocessing)

# 计算模型在给定图像上的鲁棒性
attack = foolbox.attacks.LinfPGD()
adversarials = attack(fmodel, image, label, epsilons=[0.1, 0.2, 0.3])

labels = np.argmax(fmodel(image).cpu())
adv_labels=[]
print(adversarials)
for adv in adversarials:
    adv_labels.append(np.argmax(fmodel(adv)))
robustness = np.mean(adv_labels == labels)

# 输出结果
print(f"Robustness: {robustness:.2%}")

: 